# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Set(object):
    def setupUi(self, Set):
        Set.setObjectName("Set")
        Set.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Set.sizePolicy().hasHeightForWidth())
        Set.setSizePolicy(sizePolicy)
        Set.setMinimumSize(QtCore.QSize(1000, 800))
        Set.setMaximumSize(QtCore.QSize(1200, 900))
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(Set)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox = QtWidgets.QGroupBox(Set)
        self.groupBox.setStyleSheet("font: 14pt \"楷体\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.x_lift = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_lift.sizePolicy().hasHeightForWidth())
        self.x_lift.setSizePolicy(sizePolicy)
        self.x_lift.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.x_lift.setCheckable(True)
        self.x_lift.setObjectName("x_lift")
        self.horizontalLayout.addWidget(self.x_lift)
        self.x_right = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_right.sizePolicy().hasHeightForWidth())
        self.x_right.setSizePolicy(sizePolicy)
        self.x_right.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.x_right.setCheckable(True)
        self.x_right.setObjectName("x_right")
        self.horizontalLayout.addWidget(self.x_right)
        self.x_home = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_home.sizePolicy().hasHeightForWidth())
        self.x_home.setSizePolicy(sizePolicy)
        self.x_home.setStyleSheet("background-color: rgb(207, 207, 207);;")
        self.x_home.setCheckable(True)
        self.x_home.setObjectName("x_home")
        self.horizontalLayout.addWidget(self.x_home)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.y_up = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_up.sizePolicy().hasHeightForWidth())
        self.y_up.setSizePolicy(sizePolicy)
        self.y_up.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.y_up.setCheckable(True)
        self.y_up.setObjectName("y_up")
        self.horizontalLayout_2.addWidget(self.y_up)
        self.y_down = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_down.sizePolicy().hasHeightForWidth())
        self.y_down.setSizePolicy(sizePolicy)
        self.y_down.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.y_down.setCheckable(True)
        self.y_down.setObjectName("y_down")
        self.horizontalLayout_2.addWidget(self.y_down)
        self.y_home = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_home.sizePolicy().hasHeightForWidth())
        self.y_home.setSizePolicy(sizePolicy)
        self.y_home.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.y_home.setCheckable(True)
        self.y_home.setObjectName("y_home")
        self.horizontalLayout_2.addWidget(self.y_home)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.z_cw = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_cw.sizePolicy().hasHeightForWidth())
        self.z_cw.setSizePolicy(sizePolicy)
        self.z_cw.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.z_cw.setCheckable(True)
        self.z_cw.setObjectName("z_cw")
        self.horizontalLayout_3.addWidget(self.z_cw)
        self.z_ccw = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_ccw.sizePolicy().hasHeightForWidth())
        self.z_ccw.setSizePolicy(sizePolicy)
        self.z_ccw.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.z_ccw.setCheckable(True)
        self.z_ccw.setObjectName("z_ccw")
        self.horizontalLayout_3.addWidget(self.z_ccw)
        self.z_home = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_home.sizePolicy().hasHeightForWidth())
        self.z_home.setSizePolicy(sizePolicy)
        self.z_home.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.z_home.setCheckable(True)
        self.z_home.setObjectName("z_home")
        self.horizontalLayout_3.addWidget(self.z_home)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.f_open = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_open.sizePolicy().hasHeightForWidth())
        self.f_open.setSizePolicy(sizePolicy)
        self.f_open.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.f_open.setCheckable(True)
        self.f_open.setObjectName("f_open")
        self.horizontalLayout_4.addWidget(self.f_open)
        self.f_close = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_close.sizePolicy().hasHeightForWidth())
        self.f_close.setSizePolicy(sizePolicy)
        self.f_close.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.f_close.setCheckable(True)
        self.f_close.setObjectName("f_close")
        self.horizontalLayout_4.addWidget(self.f_close)
        self.p_shrink = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_shrink.sizePolicy().hasHeightForWidth())
        self.p_shrink.setSizePolicy(sizePolicy)
        self.p_shrink.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.p_shrink.setCheckable(True)
        self.p_shrink.setObjectName("p_shrink")
        self.horizontalLayout_4.addWidget(self.p_shrink)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.b_open = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_open.sizePolicy().hasHeightForWidth())
        self.b_open.setSizePolicy(sizePolicy)
        self.b_open.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.b_open.setCheckable(True)
        self.b_open.setObjectName("b_open")
        self.horizontalLayout_5.addWidget(self.b_open)
        self.b_close = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_close.sizePolicy().hasHeightForWidth())
        self.b_close.setSizePolicy(sizePolicy)
        self.b_close.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.b_close.setCheckable(True)
        self.b_close.setObjectName("b_close")
        self.horizontalLayout_5.addWidget(self.b_close)
        self.p_stretch = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_stretch.sizePolicy().hasHeightForWidth())
        self.p_stretch.setSizePolicy(sizePolicy)
        self.p_stretch.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.p_stretch.setCheckable(True)
        self.p_stretch.setObjectName("p_stretch")
        self.horizontalLayout_5.addWidget(self.p_stretch)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.i_shrink = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_shrink.sizePolicy().hasHeightForWidth())
        self.i_shrink.setSizePolicy(sizePolicy)
        self.i_shrink.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.i_shrink.setCheckable(True)
        self.i_shrink.setObjectName("i_shrink")
        self.horizontalLayout_6.addWidget(self.i_shrink)
        self.i_stretch = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_stretch.sizePolicy().hasHeightForWidth())
        self.i_stretch.setSizePolicy(sizePolicy)
        self.i_stretch.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.i_stretch.setCheckable(True)
        self.i_stretch.setObjectName("i_stretch")
        self.horizontalLayout_6.addWidget(self.i_stretch)
        self.esc = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esc.sizePolicy().hasHeightForWidth())
        self.esc.setSizePolicy(sizePolicy)
        self.esc.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.esc.setCheckable(False)
        self.esc.setObjectName("esc")
        self.horizontalLayout_6.addWidget(self.esc)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.start.setCheckable(True)
        self.start.setObjectName("start")
        self.horizontalLayout_7.addWidget(self.start)
        self.unlock = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unlock.sizePolicy().hasHeightForWidth())
        self.unlock.setSizePolicy(sizePolicy)
        self.unlock.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.unlock.setCheckable(True)
        self.unlock.setObjectName("unlock")
        self.horizontalLayout_7.addWidget(self.unlock)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Set)
        self.groupBox_2.setStyleSheet("font: 14pt \"楷体\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.noodle_reset = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noodle_reset.sizePolicy().hasHeightForWidth())
        self.noodle_reset.setSizePolicy(sizePolicy)
        self.noodle_reset.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.noodle_reset.setCheckable(True)
        self.noodle_reset.setObjectName("noodle_reset")
        self.horizontalLayout_8.addWidget(self.noodle_reset)
        self.noodle_num = QtWidgets.QLabel(self.groupBox_2)
        self.noodle_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.noodle_num.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.noodle_num.setAlignment(QtCore.Qt.AlignCenter)
        self.noodle_num.setObjectName("noodle_num")
        self.horizontalLayout_8.addWidget(self.noodle_num)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sauce_reset = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sauce_reset.sizePolicy().hasHeightForWidth())
        self.sauce_reset.setSizePolicy(sizePolicy)
        self.sauce_reset.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.sauce_reset.setCheckable(True)
        self.sauce_reset.setObjectName("sauce_reset")
        self.horizontalLayout_9.addWidget(self.sauce_reset)
        self.sauce_num = QtWidgets.QLabel(self.groupBox_2)
        self.sauce_num.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.sauce_num.setAlignment(QtCore.Qt.AlignCenter)
        self.sauce_num.setObjectName("sauce_num")
        self.horizontalLayout_9.addWidget(self.sauce_num)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.water_reset = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.water_reset.sizePolicy().hasHeightForWidth())
        self.water_reset.setSizePolicy(sizePolicy)
        self.water_reset.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.water_reset.setCheckable(True)
        self.water_reset.setObjectName("water_reset")
        self.horizontalLayout_10.addWidget(self.water_reset)
        self.water_num = QtWidgets.QLabel(self.groupBox_2)
        self.water_num.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.water_num.setAlignment(QtCore.Qt.AlignCenter)
        self.water_num.setObjectName("water_num")
        self.horizontalLayout_10.addWidget(self.water_num)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.heat_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heat_time.sizePolicy().hasHeightForWidth())
        self.heat_time.setSizePolicy(sizePolicy)
        self.heat_time.setAlignment(QtCore.Qt.AlignCenter)
        self.heat_time.setDecimals(1)
        self.heat_time.setSingleStep(0.1)
        self.heat_time.setObjectName("heat_time")
        self.horizontalLayout_11.addWidget(self.heat_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_18.addWidget(self.label_5)
        self.water_into_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.water_into_time.sizePolicy().hasHeightForWidth())
        self.water_into_time.setSizePolicy(sizePolicy)
        self.water_into_time.setAlignment(QtCore.Qt.AlignCenter)
        self.water_into_time.setDecimals(1)
        self.water_into_time.setSingleStep(0.1)
        self.water_into_time.setObjectName("water_into_time")
        self.horizontalLayout_18.addWidget(self.water_into_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_17.addWidget(self.label_6)
        self.water_out_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.water_out_time.sizePolicy().hasHeightForWidth())
        self.water_out_time.setSizePolicy(sizePolicy)
        self.water_out_time.setAlignment(QtCore.Qt.AlignCenter)
        self.water_out_time.setDecimals(1)
        self.water_out_time.setSingleStep(0.1)
        self.water_out_time.setObjectName("water_out_time")
        self.horizontalLayout_17.addWidget(self.water_out_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.open_door_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_door_time.sizePolicy().hasHeightForWidth())
        self.open_door_time.setSizePolicy(sizePolicy)
        self.open_door_time.setAlignment(QtCore.Qt.AlignCenter)
        self.open_door_time.setDecimals(1)
        self.open_door_time.setSingleStep(0.1)
        self.open_door_time.setObjectName("open_door_time")
        self.horizontalLayout_16.addWidget(self.open_door_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.sesame_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sesame_time.sizePolicy().hasHeightForWidth())
        self.sesame_time.setSizePolicy(sizePolicy)
        self.sesame_time.setAlignment(QtCore.Qt.AlignCenter)
        self.sesame_time.setDecimals(1)
        self.sesame_time.setSingleStep(0.1)
        self.sesame_time.setObjectName("sesame_time")
        self.horizontalLayout_14.addWidget(self.sesame_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.sauce_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sauce_time.sizePolicy().hasHeightForWidth())
        self.sauce_time.setSizePolicy(sizePolicy)
        self.sauce_time.setAlignment(QtCore.Qt.AlignCenter)
        self.sauce_time.setDecimals(1)
        self.sauce_time.setSingleStep(0.1)
        self.sauce_time.setObjectName("sauce_time")
        self.horizontalLayout_13.addWidget(self.sauce_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.pepper_time = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pepper_time.sizePolicy().hasHeightForWidth())
        self.pepper_time.setSizePolicy(sizePolicy)
        self.pepper_time.setAlignment(QtCore.Qt.AlignCenter)
        self.pepper_time.setDecimals(1)
        self.pepper_time.setSingleStep(0.1)
        self.pepper_time.setObjectName("pepper_time")
        self.horizontalLayout_12.addWidget(self.pepper_time)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addWidget(self.groupBox_2)

        self.retranslateUi(Set)
        QtCore.QMetaObject.connectSlotsByName(Set)

    def retranslateUi(self, Set):
        _translate = QtCore.QCoreApplication.translate
        Set.setWindowTitle(_translate("Set", "设置"))
        self.groupBox.setTitle(_translate("Set", "调试"))
        self.x_lift.setText(_translate("Set", "X-左"))
        self.x_right.setText(_translate("Set", "X-右"))
        self.x_home.setText(_translate("Set", "X-原点"))
        self.y_up.setText(_translate("Set", "Y-上"))
        self.y_down.setText(_translate("Set", "Y-下"))
        self.y_home.setText(_translate("Set", "Y-原点"))
        self.z_cw.setText(_translate("Set", "Z-正转"))
        self.z_ccw.setText(_translate("Set", "Z-反转"))
        self.z_home.setText(_translate("Set", "Z-原点"))
        self.f_open.setText(_translate("Set", "前门开"))
        self.f_close.setText(_translate("Set", "前门关"))
        self.p_shrink.setText(_translate("Set", "推杆收"))
        self.b_open.setText(_translate("Set", "后门开"))
        self.b_close.setText(_translate("Set", "后门关"))
        self.p_stretch.setText(_translate("Set", "推杆伸"))
        self.i_shrink.setText(_translate("Set", "注料收"))
        self.i_stretch.setText(_translate("Set", "注料伸"))
        self.esc.setText(_translate("Set", "退出"))
        self.start.setText(_translate("Set", "开始"))
        self.unlock.setText(_translate("Set", "解锁"))
        self.groupBox_2.setTitle(_translate("Set", "设置"))
        self.noodle_reset.setText(_translate("Set", "面复位"))
        self.noodle_num.setText(_translate("Set", "80"))
        self.sauce_reset.setText(_translate("Set", "料复位"))
        self.sauce_num.setText(_translate("Set", "80"))
        self.water_reset.setText(_translate("Set", "水复位"))
        self.water_num.setText(_translate("Set", "80"))
        self.label_4.setText(_translate("Set", "加热时间："))
        self.heat_time.setSuffix(_translate("Set", "s"))
        self.label_5.setText(_translate("Set", "注水时间："))
        self.water_into_time.setSuffix(_translate("Set", "s"))
        self.label_6.setText(_translate("Set", "抽水时间："))
        self.water_out_time.setSuffix(_translate("Set", "s"))
        self.label_7.setText(_translate("Set", "开门时间："))
        self.open_door_time.setSuffix(_translate("Set", "s"))
        self.label_8.setText(_translate("Set", "芝麻酱时间："))
        self.sesame_time.setSuffix(_translate("Set", "s"))
        self.label_9.setText(_translate("Set", "酱油时间："))
        self.sauce_time.setSuffix(_translate("Set", "s"))
        self.label_10.setText(_translate("Set", "辣椒油时间"))
        self.pepper_time.setSuffix(_translate("Set", "s"))

